name: 'Mod Uploader'
author: 'Bobby Shmurner'
description: 'Used to Upload Mods to the Beat Saber Quest Mods Repository'
inputs:
  token:
    description: 'Your Github Token'
    required: true
  repo-token:
    description: 'A Personal Access Token that grants access to repos'
    required: true
  mod-json:
    description: 'Path to the mod.json'
    default: 'mod.json'
    required: true
  qmod-name:
    description: 'Name of QMod Asset. NOTE: This is the name of the uploaded file, not the file on disk'
    required: true
  tag:
    description: 'The tag of the release'
    required: true
  cover:
    description: "URL to the author's icon. By default the URL to 'cover.png' will be used"
  author-icon:
    description: "URL to the author's icon. By default the repo's owner's pfp will be used"
  
runs:
  using: 'node16'
  main: 'index.js'