name: 'Mod Uploader'
author: 'Bobby Shmurner'
description: 'Used to Upload Mods to the Beat Saber Quest Mods Repository'
inputs:
  token:
    description: 'Your Github Token'
    required: true
  repo-token:
    description: 'A Personal Access Token that grants access to repos'
    required: true
  tag:
    description: 'The tag of the release. This is only required if qmod-url is blank'
  mod-json:
    description: 'Path to the mod.json'
    default: 'mod.json'
  cover:
    description: "URL to the cover of the mod. By default the URL to 'cover.png' will be used"
  authors:
    description: "A comma (and space: `, `) seperated list of authors. If left blank, the 'author' param from the 'mod.json' will be used"
  author-icon:
    description: "URL to the author's icon. By default the repo's owner's pfp will be used"
  qmod-name:
    description: 'Name of QMod Asset. NOTE: This is the name of the uploaded file, not the file on disk'
  qmod-url:
    description: 'A custom URL to a qmod. This is mutually exclusive with "qmod-name"'
  note:
    description: 'A custom note to pass to the PR message'

runs:
  using: 'node16'
  main: 'dist/index.js'
